---
# Default settings for Grafana Docker deployment
grafana_workspace: /opt/grafana
grafana_image: grafana/grafana:10.4.6
grafana_domain: grafana.svc.plus
grafana_protocol: http
grafana_host_port: 3000
grafana_admin_user: admin
grafana_admin_password: admin
